var app = angular.module("wc", []);


app.controller("wcController", ["$scope", function($scope) {

  $scope.data = [{
    countryName: "Andorra",
    population: "84000",
    continent: "EU"
  }, {
    "countryName": "United Arab Emirates",
    "population": "4975593",
    "continent": "AS"
  }, {
    "countryName": "Afghanistan",
    "population": "29121286",
    "continent": "AS"
  }, {
    "countryName": "Antigua and Barbuda",
    "population": "86754",
    "continent": "NA"
  }, {
    "countryName": "Anguilla",
    "population": "13254",
    "continent": "NA"
  }, {
    "countryName": "Albania",
    "population": "2986952",
    "continent": "EU"
  }, {
    "countryName": "Armenia",
    "population": "2968000",
    "continent": "AS"
  }, {
    "countryName": "Angola",
    "population": "13068161",
    "continent": "AF"
  }, {
    "countryName": "Antarctica",
    "population": "0",
    "continent": "AN"
  }, {
    "countryName": "Argentina",
    "population": "41343201",
    "continent": "SA"
  }, {
    "countryName": "American Samoa",
    "population": "57881",
    "continent": "OC"
  }, {
    "countryName": "Austria",
    "population": "8205000",
    "continent": "EU"
  }, {
    "countryName": "Australia",
    "population": "21515754",
    "continent": "OC"
  }, {
    "countryName": "Aruba",
    "population": "71566",
    "continent": "NA"
  }, {
    "countryName": "Åland",
    "population": "26711",
    "continent": "EU"
  }, {
    "countryName": "Azerbaijan",
    "population": "8303512",
    "continent": "AS"
  }, {
    "countryName": "Bosnia and Herzegovina",
    "population": "4590000",
    "continent": "EU"
  }, {
    "countryName": "Barbados",
    "population": "285653",
    "continent": "NA"
  }, {
    "countryName": "Bangladesh",
    "population": "156118464",
    "continent": "AS"
  }, {
    "countryName": "Belgium",
    "population": "10403000",
    "continent": "EU"
  }, {
    "countryName": "Burkina Faso",
    "population": "16241811",
    "continent": "AF"
  }, {
    "countryName": "Bulgaria",
    "population": "7148785",
    "continent": "EU"
  }, {
    "countryName": "Bahrain",
    "population": "738004",
    "continent": "AS"
  }, {
    "countryName": "Burundi",
    "population": "9863117",
    "continent": "AF"
  }, {
    "countryName": "Benin",
    "population": "9056010",
    "continent": "AF"
  }, {
    "countryName": "Saint Barthélemy",
    "population": "8450",
    "continent": "NA"
  }, {
    "countryName": "Bermuda",
    "population": "65365",
    "continent": "NA"
  }, {
    "countryName": "Brunei",
    "population": "395027",
    "continent": "AS"
  }, {
    "countryName": "Bolivia",
    "population": "9947418",
    "continent": "SA"
  }, {
    "countryName": "Bonaire",
    "population": "18012",
    "continent": "NA"
  }, {
    "countryName": "Brazil",
    "population": "201103330",
    "continent": "SA"
  }, {
    "countryName": "Bahamas",
    "population": "301790",
    "continent": "NA"
  }, {
    "countryName": "Bhutan",
    "population": "699847",
    "continent": "AS"
  }, {
    "countryName": "Bouvet Island",
    "population": "0",
    "continent": "AN"
  }, {
    "countryName": "Botswana",
    "population": "2029307",
    "continent": "AF"
  }, {
    "countryName": "Belarus",
    "population": "9685000",
    "continent": "EU"
  }, {
    "countryName": "Belize",
    "population": "314522",
    "continent": "NA"
  }, {
    "countryName": "Canada",
    "population": "33679000",
    "continent": "NA"
  }, {
    "countryName": "Cocos [Keeling] Islands",
    "population": "628",
    "continent": "AS"
  }, {
    "countryName": "Democratic Republic of the Congo",
    "population": "70916439",
    "continent": "AF"
  }, {
    "countryName": "Central African Republic",
    "population": "4844927",
    "continent": "AF"
  }, {
    "countryName": "Republic of the Congo",
    "population": "3039126",
    "continent": "AF"
  }, {
    "countryName": "Switzerland",
    "population": "7581000",
    "continent": "EU"
  }, {
    "countryName": "Ivory Coast",
    "population": "21058798",
    "continent": "AF"
  }, {
    "countryName": "Cook Islands",
    "population": "21388",
    "continent": "OC"
  }, {
    "countryName": "Chile",
    "population": "16746491",
    "continent": "SA"
  }, {
    "countryName": "Cameroon",
    "population": "19294149",
    "continent": "AF"
  }, {
    "countryName": "China",
    "population": "1330044000",
    "continent": "AS"
  }, {
    "countryName": "Colombia",
    "population": "47790000",
    "continent": "SA"
  }, {
    "countryName": "Costa Rica",
    "population": "4516220",
    "continent": "NA"
  }, {
    "countryName": "Cuba",
    "population": "11423000",
    "continent": "NA"
  }, {
    "countryName": "Cape Verde",
    "population": "508659",
    "continent": "AF"
  }, {
    "countryName": "Curacao",
    "population": "141766",
    "continent": "NA"
  }, {
    "countryName": "Christmas Island",
    "population": "1500",
    "continent": "AS"
  }, {
    "countryName": "Cyprus",
    "population": "1102677",
    "continent": "EU"
  }, {
    "countryName": "Czech Republic",
    "population": "10476000",
    "continent": "EU"
  }, {
    "countryName": "Germany",
    "population": "81802257",
    "continent": "EU"
  }, {
    "countryName": "Djibouti",
    "population": "740528",
    "continent": "AF"
  }, {
    "countryName": "Denmark",
    "population": "5484000",
    "continent": "EU"
  }, {
    "countryName": "Dominica",
    "population": "72813",
    "continent": "NA"
  }, {
    "countryName": "Dominican Republic",
    "population": "9823821",
    "continent": "NA"
  }, {
    "countryName": "Algeria",
    "population": "34586184",
    "continent": "AF"
  }, {
    "countryName": "Ecuador",
    "population": "14790608",
    "continent": "SA"
  }, {
    "countryName": "Estonia",
    "population": "1291170",
    "continent": "EU"
  }, {
    "countryName": "Egypt",
    "population": "80471869",
    "continent": "AF"
  }, {
    "countryName": "Western Sahara",
    "population": "273008",
    "continent": "AF"
  }, {
    "countryName": "Eritrea",
    "population": "5792984",
    "continent": "AF"
  }, {
    "countryName": "Spain",
    "population": "46505963",
    "continent": "EU"
  }, {
    "countryName": "Ethiopia",
    "population": "88013491",
    "continent": "AF"
  }, {
    "countryName": "Finland",
    "population": "5244000",
    "continent": "EU"
  }, {
    "countryName": "Fiji",
    "population": "875983",
    "continent": "OC"
  }, {
    "countryName": "Falkland Islands",
    "population": "2638",
    "continent": "SA"
  }, {
    "countryName": "Micronesia",
    "population": "107708",
    "continent": "OC"
  }, {
    "countryName": "Faroe Islands",
    "population": "48228",
    "continent": "EU"
  }, {
    "countryName": "France",
    "population": "64768389",
    "continent": "EU"
  }, {
    "countryName": "Gabon",
    "population": "1545255",
    "continent": "AF"
  }, {
    "countryName": "United Kingdom",
    "population": "62348447",
    "continent": "EU"
  }, {
    "countryName": "Grenada",
    "population": "107818",
    "continent": "NA"
  }, {
    "countryName": "Georgia",
    "population": "4630000",
    "continent": "AS"
  }, {
    "countryName": "French Guiana",
    "population": "195506",
    "continent": "SA"
  }, {
    "countryName": "Guernsey",
    "population": "65228",
    "continent": "EU"
  }, {
    "countryName": "Ghana",
    "population": "24339838",
    "continent": "AF"
  }, {
    "countryName": "Gibraltar",
    "population": "27884",
    "continent": "EU"
  }, {
    "countryName": "Greenland",
    "population": "56375",
    "continent": "NA"
  }, {
    "countryName": "Gambia",
    "population": "1593256",
    "continent": "AF"
  }, {
    "countryName": "Guinea",
    "population": "10324025",
    "continent": "AF"
  }, {
    "countryName": "Guadeloupe",
    "population": "443000",
    "continent": "NA"
  }, {
    "countryName": "Equatorial Guinea",
    "population": "1014999",
    "continent": "AF"
  }, {
    "countryName": "Greece",
    "population": "11000000",
    "continent": "EU"
  }, {
    "countryName": "South Georgia and the South Sandwich Islands",
    "population": "30",
    "continent": "AN"
  }, {
    "countryName": "Guatemala",
    "population": "13550440",
    "continent": "NA"
  }, {
    "countryName": "Guam",
    "population": "159358",
    "continent": "OC"
  }, {
    "countryName": "Guinea-Bissau",
    "population": "1565126",
    "continent": "AF"
  }, {
    "countryName": "Guyana",
    "population": "748486",
    "continent": "SA"
  }, {
    "countryName": "Hong Kong",
    "population": "6898686",
    "continent": "AS"
  }, {
    "countryName": "Heard Island and McDonald Islands",
    "population": "0",
    "continent": "AN"
  }, {
    "countryName": "Honduras",
    "population": "7989415",
    "continent": "NA"
  }, {
    "countryName": "Croatia",
    "population": "4491000",
    "continent": "EU"
  }, {
    "countryName": "Haiti",
    "population": "9648924",
    "continent": "NA"
  }, {
    "countryName": "Hungary",
    "population": "9982000",
    "continent": "EU"
  }, {
    "countryName": "Indonesia",
    "population": "242968342",
    "continent": "AS"
  }, {
    "countryName": "Ireland",
    "population": "4622917",
    "continent": "EU"
  }, {
    "countryName": "Israel",
    "population": "7353985",
    "continent": "AS"
  }, {
    "countryName": "Isle of Man",
    "population": "75049",
    "continent": "EU"
  }, {
    "countryName": "India",
    "population": "1173108018",
    "continent": "AS"
  }, {
    "countryName": "British Indian Ocean Territory",
    "population": "4000",
    "continent": "AS"
  }, {
    "countryName": "Iraq",
    "population": "29671605",
    "continent": "AS"
  }, {
    "countryName": "Iran",
    "population": "76923300",
    "continent": "AS"
  }, {
    "countryName": "Iceland",
    "population": "308910",
    "continent": "EU"
  }, {
    "countryName": "Italy",
    "population": "60340328",
    "continent": "EU"
  }, {
    "countryName": "Jersey",
    "population": "90812",
    "continent": "EU"
  }, {
    "countryName": "Jamaica",
    "population": "2847232",
    "continent": "NA"
  }, {
    "countryName": "Jordan",
    "population": "6407085",
    "continent": "AS"
  }, {
    "countryName": "Japan",
    "population": "127288000",
    "continent": "AS"
  }, {
    "countryName": "Kenya",
    "population": "40046566",
    "continent": "AF"
  }, {
    "countryName": "Kyrgyzstan",
    "population": "5776500",
    "continent": "AS"
  }, {
    "countryName": "Cambodia",
    "population": "14453680",
    "continent": "AS"
  }, {
    "countryName": "Kiribati",
    "population": "92533",
    "continent": "OC"
  }, {
    "countryName": "Comoros",
    "population": "773407",
    "continent": "AF"
  }, {
    "countryName": "Saint Kitts and Nevis",
    "population": "51134",
    "continent": "NA"
  }, {
    "countryName": "North Korea",
    "population": "22912177",
    "continent": "AS"
  }, {
    "countryName": "South Korea",
    "population": "48422644",
    "continent": "AS"
  }, {
    "countryName": "Kuwait",
    "population": "2789132",
    "continent": "AS"
  }, {
    "countryName": "Cayman Islands",
    "population": "44270",
    "continent": "NA"
  }, {
    "countryName": "Kazakhstan",
    "population": "15340000",
    "continent": "AS"
  }, {
    "countryName": "Laos",
    "population": "6368162",
    "continent": "AS"
  }, {
    "countryName": "Lebanon",
    "population": "4125247",
    "continent": "AS"
  }, {
    "countryName": "Saint Lucia",
    "population": "160922",
    "continent": "NA"
  }, {
    "countryName": "Liechtenstein",
    "population": "35000",
    "continent": "EU"
  }, {
    "countryName": "Sri Lanka",
    "population": "21513990",
    "continent": "AS"
  }, {
    "countryName": "Liberia",
    "population": "3685076",
    "continent": "AF"
  }, {
    "countryName": "Lesotho",
    "population": "1919552",
    "continent": "AF"
  }, {
    "countryName": "Lithuania",
    "population": "2944459",
    "continent": "EU"
  }, {
    "countryName": "Luxembourg",
    "population": "497538",
    "continent": "EU"
  }, {
    "countryName": "Latvia",
    "population": "2217969",
    "continent": "EU"
  }, {
    "countryName": "Libya",
    "population": "6461454",
    "continent": "AF"
  }, {
    "countryName": "Morocco",
    "population": "31627428",
    "continent": "AF"
  }, {
    "countryName": "Monaco",
    "population": "32965",
    "continent": "EU"
  }, {
    "countryName": "Moldova",
    "population": "4324000",
    "continent": "EU"
  }, {
    "countryName": "Montenegro",
    "population": "666730",
    "continent": "EU"
  }, {
    "countryName": "Saint Martin",
    "population": "35925",
    "continent": "NA"
  }, {
    "countryName": "Madagascar",
    "population": "21281844",
    "continent": "AF"
  }, {
    "countryName": "Marshall Islands",
    "population": "65859",
    "continent": "OC"
  }, {
    "countryName": "Macedonia",
    "population": "2062294",
    "continent": "EU"
  }, {
    "countryName": "Mali",
    "population": "13796354",
    "continent": "AF"
  }, {
    "countryName": "Myanmar [Burma]",
    "population": "53414374",
    "continent": "AS"
  }, {
    "countryName": "Mongolia",
    "population": "3086918",
    "continent": "AS"
  }, {
    "countryName": "Macao",
    "population": "449198",
    "continent": "AS"
  }, {
    "countryName": "Northern Mariana Islands",
    "population": "53883",
    "continent": "OC"
  }, {
    "countryName": "Martinique",
    "population": "432900",
    "continent": "NA"
  }, {
    "countryName": "Mauritania",
    "population": "3205060",
    "continent": "AF"
  }, {
    "countryName": "Montserrat",
    "population": "9341",
    "continent": "NA"
  }, {
    "countryName": "Malta",
    "population": "403000",
    "continent": "EU"
  }, {
    "countryName": "Mauritius",
    "population": "1294104",
    "continent": "AF"
  }, {
    "countryName": "Maldives",
    "population": "395650",
    "continent": "AS"
  }, {
    "countryName": "Malawi",
    "population": "15447500",
    "continent": "AF"
  }, {
    "countryName": "Mexico",
    "population": "112468855",
    "continent": "NA"
  }, {
    "countryName": "Malaysia",
    "population": "28274729",
    "continent": "AS"
  }, {
    "countryName": "Mozambique",
    "population": "22061451",
    "continent": "AF"
  }, {
    "countryName": "Namibia",
    "population": "2128471",
    "continent": "AF"
  }, {
    "countryName": "New Caledonia",
    "population": "216494",
    "continent": "OC"
  }, {
    "countryName": "Niger",
    "population": "15878271",
    "continent": "AF"
  }, {
    "countryName": "Norfolk Island",
    "population": "1828",
    "continent": "OC"
  }, {
    "countryName": "Nigeria",
    "population": "154000000",
    "continent": "AF"
  }, {
    "countryName": "Nicaragua",
    "population": "5995928",
    "continent": "NA"
  }, {
    "countryName": "Netherlands",
    "population": "16645000",
    "continent": "EU"
  }, {
    "countryName": "Norway",
    "population": "5009150",
    "continent": "EU"
  }, {
    "countryName": "Nepal",
    "population": "28951852",
    "continent": "AS"
  }, {
    "countryName": "Nauru",
    "population": "10065",
    "continent": "OC"
  }, {
    "countryName": "Niue",
    "population": "2166",
    "continent": "OC"
  }, {
    "countryName": "New Zealand",
    "population": "4252277",
    "continent": "OC"
  }, {
    "countryName": "Oman",
    "population": "2967717",
    "continent": "AS"
  }, {
    "countryName": "Panama",
    "population": "3410676",
    "continent": "NA"
  }, {
    "countryName": "Peru",
    "population": "29907003",
    "continent": "SA"
  }, {
    "countryName": "French Polynesia",
    "population": "270485",
    "continent": "OC"
  }, {
    "countryName": "Papua New Guinea",
    "population": "6064515",
    "continent": "OC"
  }, {
    "countryName": "Philippines",
    "population": "99900177",
    "continent": "AS"
  }, {
    "countryName": "Pakistan",
    "population": "184404791",
    "continent": "AS"
  }, {
    "countryName": "Poland",
    "population": "38500000",
    "continent": "EU"
  }, {
    "countryName": "Saint Pierre and Miquelon",
    "population": "7012",
    "continent": "NA"
  }, {
    "countryName": "Pitcairn Islands",
    "population": "46",
    "continent": "OC"
  }, {
    "countryName": "Puerto Rico",
    "population": "3916632",
    "continent": "NA"
  }, {
    "countryName": "Palestine",
    "population": "3800000",
    "continent": "AS"
  }, {
    "countryName": "Portugal",
    "population": "10676000",
    "continent": "EU"
  }, {
    "countryName": "Palau",
    "population": "19907",
    "continent": "OC"
  }, {
    "countryName": "Paraguay",
    "population": "6375830",
    "continent": "SA"
  }, {
    "countryName": "Qatar",
    "population": "840926",
    "continent": "AS"
  }, {
    "countryName": "Réunion",
    "population": "776948",
    "continent": "AF"
  }, {
    "countryName": "Romania",
    "population": "21959278",
    "continent": "EU"
  }, {
    "countryName": "Serbia",
    "population": "7344847",
    "continent": "EU"
  }, {
    "countryName": "Russia",
    "population": "140702000",
    "continent": "EU"
  }, {
    "countryName": "Rwanda",
    "population": "11055976",
    "continent": "AF"
  }, {
    "countryName": "Saudi Arabia",
    "population": "25731776",
    "continent": "AS"
  }, {
    "countryName": "Solomon Islands",
    "population": "559198",
    "continent": "OC"
  }, {
    "countryName": "Seychelles",
    "population": "88340",
    "continent": "AF"
  }, {
    "countryName": "Sudan",
    "population": "35000000",
    "continent": "AF"
  }, {
    "countryName": "Sweden",
    "population": "9555893",
    "continent": "EU"
  }, {
    "countryName": "Singapore",
    "population": "4701069",
    "continent": "AS"
  }, {
    "countryName": "Saint Helena",
    "population": "7460",
    "continent": "AF"
  }, {
    "countryName": "Slovenia",
    "population": "2007000",
    "continent": "EU"
  }, {
    "countryName": "Svalbard and Jan Mayen",
    "population": "2550",
    "continent": "EU"
  }, {
    "countryName": "Slovakia",
    "population": "5455000",
    "continent": "EU"
  }, {
    "countryName": "Sierra Leone",
    "population": "5245695",
    "continent": "AF"
  }, {
    "countryName": "San Marino",
    "population": "31477",
    "continent": "EU"
  }, {
    "countryName": "Senegal",
    "population": "12323252",
    "continent": "AF"
  }, {
    "countryName": "Somalia",
    "population": "10112453",
    "continent": "AF"
  }, {
    "countryName": "Suriname",
    "population": "492829",
    "continent": "SA"
  }, {
    "countryName": "South Sudan",
    "population": "8260490",
    "continent": "AF"
  }, {
    "countryName": "São Tomé and Príncipe",
    "population": "175808",
    "continent": "AF"
  }, {
    "countryName": "El Salvador",
    "population": "6052064",
    "continent": "NA"
  }, {
    "countryName": "Sint Maarten",
    "population": "37429",
    "continent": "NA"
  }, {
    "countryName": "Syria",
    "population": "22198110",
    "continent": "AS"
  }, {
    "countryName": "Swaziland",
    "population": "1354051",
    "continent": "AF"
  }, {
    "countryName": "Turks and Caicos Islands",
    "population": "20556",
    "continent": "NA"
  }, {
    "countryName": "Chad",
    "population": "10543464",
    "continent": "AF"
  }, {
    "countryName": "French Southern Territories",
    "population": "140",
    "continent": "AN"
  }, {
    "countryName": "Togo",
    "population": "6587239",
    "continent": "AF"
  }, {
    "countryName": "Thailand",
    "population": "67089500",
    "continent": "AS"
  }, {
    "countryName": "Tajikistan",
    "population": "7487489",
    "continent": "AS"
  }, {
    "countryName": "Tokelau",
    "population": "1466",
    "continent": "OC"
  }, {
    "countryName": "East Timor",
    "population": "1154625",
    "continent": "OC"
  }, {
    "countryName": "Turkmenistan",
    "population": "4940916",
    "continent": "AS"
  }, {
    "countryName": "Tunisia",
    "population": "10589025",
    "continent": "AF"
  }, {
    "countryName": "Tonga",
    "population": "122580",
    "continent": "OC"
  }, {
    "countryName": "Turkey",
    "population": "77804122",
    "continent": "AS"
  }, {
    "countryName": "Trinidad and Tobago",
    "population": "1228691",
    "continent": "NA"
  }, {
    "countryName": "Tuvalu",
    "population": "10472",
    "continent": "OC"
  }, {
    "countryName": "Taiwan",
    "population": "22894384",
    "continent": "AS"
  }, {
    "countryName": "Tanzania",
    "population": "41892895",
    "continent": "AF"
  }, {
    "countryName": "Ukraine",
    "population": "45415596",
    "continent": "EU"
  }, {
    "countryName": "Uganda",
    "population": "33398682",
    "continent": "AF"
  }, {
    "countryName": "U.S. Minor Outlying Islands",
    "population": "0",
    "continent": "OC"
  }, {
    "countryName": "United States",
    "population": "310232863",
    "continent": "NA"
  }, {
    "countryName": "Uruguay",
    "population": "3477000",
    "continent": "SA"
  }, {
    "countryName": "Uzbekistan",
    "population": "27865738",
    "continent": "AS"
  }, {
    "countryName": "Vatican City",
    "population": "921",
    "continent": "EU"
  }, {
    "countryName": "Saint Vincent and the Grenadines",
    "population": "104217",
    "continent": "NA"
  }, {
    "countryName": "Venezuela",
    "population": "27223228",
    "continent": "SA"
  }, {
    "countryName": "British Virgin Islands",
    "population": "21730",
    "continent": "NA"
  }, {
    "countryName": "U.S. Virgin Islands",
    "population": "108708",
    "continent": "NA"
  }, {
    "countryName": "Vietnam",
    "population": "89571130",
    "continent": "AS"
  }, {
    "countryName": "Vanuatu",
    "population": "221552",
    "continent": "OC"
  }, {
    "countryName": "Wallis and Futuna",
    "population": "16025",
    "continent": "OC"
  }, {
    "countryName": "Samoa",
    "population": "192001",
    "continent": "OC"
  }, {
    "countryName": "Kosovo",
    "population": "1800000",
    "continent": "EU"
  }, {
    "countryName": "Yemen",
    "population": "23495361",
    "continent": "AS"
  }, {
    "countryName": "Mayotte",
    "population": "159042",
    "continent": "AF"
  }, {
    "countryName": "South Africa",
    "population": "49000000",
    "continent": "AF"
  }, {
    "countryName": "Zambia",
    "population": "13460305",
    "continent": "AF"
  }, {
    "countryName": "Zimbabwe",
    "population": "11651858",
    "continent": "AF"
  }]

}]);

